import Navbar from "../components/navbar";
import "./globals.css";
import "./fonts.css";
import Footer from "@/components/footer";

export const metadata = {
  title: "Prop Simulator",
  description: "Generated by -Hamid-Mohamdi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body className="bg-gray-900">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
