import Provider from "@/components/provider";
import Navbar from "../components/navbar";
import "../styles/globals.css";
import Footer from "@/components/footer";
import { ThemeProvider } from "next-themes";

// for SEO metadata

export const metadata = {
  title: "Prop Simulator",
  description: "Generated by -Hamid-Mohamdi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body className="bg-gray-900">
        <ThemeProvider attribute="class">
          <Provider>
            <Navbar />
            {children}
            <Footer />
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
